pipeline:
  test:
    image: golang
    commands:
      - go build ./cmd/*
      - go test

  publish:
    image: plugins/docker
    repo: seabirdchat/seabird-datadog-plugin
    secrets: [ docker_username, docker_password ]
    when:
      branch: main
